include:
  - template: SAST.gitlab-ci.yml

include:
  template: Dependency-Scanning.gitlab-ci.yml

variables:
  SAST_BANDIT_EXCLUDED_PATHS: "gcloudc/tests,test_settings.py"

python37:
  image: registry.gitlab.com/potato-oss/google-cloud/django-gcloud-connectors/python37:latest
  stage: test
  script: tox -e py37

python36:
  image: registry.gitlab.com/potato-oss/google-cloud/django-gcloud-connectors/python36:latest
  stage: test
  script: tox -e py36

